server:
  port: 8086
spring:
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  elasticsearch:
    rest:
      uris: http://121.89.194.207:9200
  application:
    name: search-service
  jackson:
    default-property-inclusion: non_null
  rabbitmq:
    host: 121.89.194.207
    port: 5672
    virtual-host: /lifeline
    username: lifeline
    password: 41312019