server:
  port: 8092

spring:
  application:
    name: order-service
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  redis:
    host: 127.0.0.1
  rabbitmq:
    host: 121.89.194.207
    port: 5672
    virtual-host: /lifeline
    username: lifeline
    password: 41312019
gmall:
  jwt:
    pubKeyPath: G:\\gmall\\rsa\\rsa.pub
    cookieName: GMALL_TOKEN

alipay:
  app_id: 2016102400751912
  merchant_private_key: MIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQCA+KyYACn911u5v/tn8i79g5lktLHXI4rSU5j6W90MRfULEBVCxFQ6gE9I8nI5DooNVsl/2mjfVy6e5UMHsY+8+i0eQZmAnrRd1XHGJ/K5oziqaVMSZkrgGOz0IbBuzcCK1ZDQVGwjGlW8AxECOS3L9wuaQy2MF9kC4wt9+yI/HNrDTfxr5MTm6TZMo3JHliPxZ4iX/H856i1WtGNuP9A6PSzmAKbbbxUiZoGy8uQQwmrY6lLRs34OKwbRNnpFGOYBSwlsV5k0sFgG8WNIFcBFkiPdAhgcGhCBIdXd4Bfaoktb2iISzQddDoC7XNBPAa1tTQCEUiT4cOVEQKwic//XAgMBAAECggEAOpO3oFoCuH5F9PnTcAS5fv90fh7r3zEPbjP1+VAb9+UWRO4LGgYd02xPlmw3oN6PqTtPzbgfhcENNbIfXbEx/b0LHQDifV6XwT6erEecoOAXbp7j0imPvHTVupRKlCjzWJtjaJvPeaoOYpRp9z6NJGSSaoA0gbqbIAqLP67+gPcsy8jRTdkURMIzLzJSwiV+T9vSFr//tWDTkPTTSIZNPn+nobu6o3zvzW7PaJ8HSi2mdpgHbawQATDgWo/tRgXD7UCNrQ23byPXx8LK95xbYiWzIDpjzSXmqUNfBAGCLvrRjvBvOotCYl8ctOpwhhv6ZN5LHwY+qAhvTQa827wKwQKBgQDV3oelXpR1gFin/GIqA+SDBIxRXz2qwKUErV4B3DvqXgIgnh+VaxqrCaWout3WreptG34tsXViad4glwtOsnGNW3H6dkT4UZb6ZQBDzRIO+iyhrmZI460iWLzWXU/lXeJhOwhOXvY62+l2z9Qla/CHRp728I49YzRQ8UovTosrMQKBgQCaYLov2HguQYthAv4728x1PZzy+yYDimFglU/yKongjjeW6FWDulTVVziyGZ6+59C1rvyY8RURzzESgcpdhkcBPd1eLKf/DeamWArMLGUtpvblbnZYhXzgirs9mkG+Gi4ma1EGkvs0fJc+NdlK6zdDAb5lPw59fF8+qyaz2WOJhwKBgQCeHKVF8dVpxRhGIQVlsHkJD5y5L+NEUKXu/kjIsUwuaY/DE4OgEI2nszsgsf39j5gHT9MJ7u8scb5Bc8ltRelDKz7pfvRgbNlkhrUaawqVvgivA2MlMgU2pkn9ZQEDPlR1s5Hhdr0tKJXCO8XIYLNzHxe40oEmCyiLSsegj729kQKBgQCSgMzwbuvOaeFNlTuTrslfUbNKW9D9dytmLwyJcpkaA5z5l07gDcpIE9f4HJwr626DnKaWteMa3ZdiSs2y56UmpoEXyCU9xQFoRxEoJdF2+4Y+wQ+KflO9+6opkeRl9g5p41ondQD0FHCrVwr5MDNnYZZAGxEzQP5aSK4X62usrQKBgDwvbbccZu9RgYvAJTLhMNkP3vudXz7oxTEnw53JmGArsqY+ZGv5Rru9q23ePh3ecFAWS8joUqrCuFfvmpqHsNf5ktuHnRhJ/DEXRKdOADQWXvNstrEvWZrfu2V6XTbAdIbTop+9V1yfdyy7QwCpBhcPvIf0t0Q830zsIPKrB4Mz
  alipay_public_key: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAvNCKk97iAUNYuRXNuUsWIv0a7B0Q9/VCkbe34261/NMIs23y+lIcbJAMRWOorsZe5VKt8Vgqp5FmUedZUYD1DbS7RDs/duSjI++umCZCjNngTRgDcyy3u2tEuXsor7yBa/we8+0JYiyIVFkAISs8c9AcI6gQG6oVrKnbMPMzErba/2wM5E2rjkO23eCdMMNB/0Epq4Jrpw40uFHxwDUuTT71slONTRcKsiMwJZP5nYc95wQCPg3yU1Hx6nfLRndOpa6tQCmwdWhbzrPQwE8kVTAHqZB/kE8eocrYfe4GCewLrGHGsfjLMxfgmxQllGsmLnp2LvIb/vGN/X86AiouwwIDAQAB
  notify_url: http://3x9msfcchd.52http.net/api/order/pay/success  # 域名是哲西云提供的域名，路径是订单支付成功回调的路径
  return_url: http://localhost:8888/pay/success.html
  sign_type: RSA2
  gatewayUrl: https://openapi.alipaydev.com/gateway.do